import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OOP Documentation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className="h-[64px] border shadow-sm sticky top-0 bg-white">
          <div className="flex container items-center h-full">
            <div className="flex font-black text-2xl my-auto">
              OOP Documentation
            </div>
          </div>
        </header>
        <main className="container w-full h-full">
          <div className="border-b">
            <div className="flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
              <aside className="fixed top-14 z-30 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 md:sticky md:block">
                <ScrollArea className="h-full py-6 lg:py-8">
                  <Sidebar />
                </ScrollArea>
              </aside>
              <div className="py-8 max-w-3xl">
                {children}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
