import Link from "next/link"

export default function Sidebar() {
  return (
    <ul className="flex h-full w-full flex-col gap-2 [&_li]:mb-0">
      <li className="font-bold">
        Introduction
      </li>
      <li>
        <Link
          className="hover:underline text-sm"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li><li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>

      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
      <li>
        <Link
          className="hover:underline"
          href="/"
        >
          Welcome
        </Link>
      </li>
    </ul>
  )
}